openapi: 3.0.0
info:
  version: 1.0.0
  title: "Credit commons: Business logic service"
  description: Internal API called by Credit Commons reference implementation
  contact:
    name: Matthew Slater
    url: http://matslats.net/contact
  license:
    name: GNU GPL
paths:
  /append:
    post:
      summary: Retrieve any dependent transactions according to business logic
      operationId: appendEntries
      requestBody:
        $ref: '../vendor/credit-commons-software-stack/cc-php-lib/docs/credit-commons-openapi-3.0.yml#components/requestBodies/Transaction'
        description: the originating entry
        required: true
      responses:
        "200":
          description: Entries to be appended.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../vendor/credit-commons-software-stack/cc-php-lib/docs/credit-commons-openapi-3.0.yml#/components/schemas/Entry'


